require "modbot/modbot"
require "modbot/version"
require "modbot/reddit_wrap"
require "modbot/modbot_fetch"
require "modbot/modbot_check"
require "modbot/modbot_score"
require "modbot/modbot_process"
require "modbot/modbot_alerts"
require "modbot/modbot_utilities"
require "logger"
#require "modbot/result_set"#fold check/score into a class w/enumerable mixin that holds the fetched results and returns values as needed
